import type { PhotoCollection } from './types';
import galleryManifest from './gallery-manifest.json';
import galleryPlacement from './gallery-placement.json';

/**
 * Photo paths are relative to public/. Gallery categories are driven by
 * gallery-manifest.json, generated by the local/cloud categorization scripts.
 *
 * Optional src/gallery-placement.json:
 * - moves: relocate an entry from one manifest category to another (same path string).
 * - order: per-category path lists to control display order (paths not listed keep their relative order after).
 */

const base = (import.meta as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
const stillLifeBase = (base.endsWith('/') ? base.slice(0, -1) : base) + '/photos/still-life';
const SUPPORTED_IMAGE_FILE = /\.(jpe?g|png|webp)$/i;
const ABOUT_KEY = 'still-life';

type GalleryManifest = {
  [category: string]: string[] | undefined;
  'still-life'?: string[];
};

type GalleryMove = {
  fromCategory: string;
  path: string;
  toCategory: string;
};

type GalleryPlacementFile = {
  moves?: GalleryMove[];
  order?: Record<string, string[] | undefined>;
};

function cloneManifest(manifest: GalleryManifest): GalleryManifest {
  const out: GalleryManifest = {};
  for (const [k, v] of Object.entries(manifest)) {
    out[k] = Array.isArray(v) ? [...v] : v;
  }
  return out;
}

function applyGalleryMoves(manifest: GalleryManifest, moves: GalleryMove[] | undefined): GalleryManifest {
  const out = cloneManifest(manifest);
  for (const m of moves ?? []) {
    const fromList = out[m.fromCategory];
    if (!Array.isArray(fromList)) continue;
    const idx = fromList.indexOf(m.path);
    if (idx < 0) continue;
    fromList.splice(idx, 1);
    if (!Array.isArray(out[m.toCategory])) out[m.toCategory] = [];
    const toList = out[m.toCategory]!;
    if (!toList.includes(m.path)) toList.push(m.path);
  }
  return out;
}

function applyOrderOverride(
  entries: string[],
  category: string,
  order: Record<string, string[] | undefined> | undefined
): string[] {
  const wish = order?.[category];
  if (!wish?.length) return entries;
  const remaining = new Set(entries);
  const next: string[] = [];
  for (const p of wish) {
    if (remaining.has(p)) {
      next.push(p);
      remaining.delete(p);
    }
  }
  for (const p of entries) {
    if (remaining.has(p)) next.push(p);
  }
  return next;
}

function toCategoryTitle(category: string): string {
  return category
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function resolveGalleryImagePath(category: string, entry: string): string {
  const normalized = entry.trim().replace(/^\/+/, '');
  if (!normalized) return '';
  if (normalized.includes('/')) return `${stillLifeBase}/${normalized}`;
  return `${stillLifeBase}/${category}/${normalized}`;
}

function photosFromEntries(entries: string[], category: string) {
  return entries.map((entry, i) => {
    const slug = entry.replace(/\.[^.]+$/, '').replace(/[^a-z0-9/_-]/gi, '_');
    return {
      id: `${category}-${i + 1}`,
      src: resolveGalleryImagePath(category, entry),
      alt: `Still life ${slug.replace(/\//g, ' ')}`,
      caption: '',
    };
  });
}

function selectGalleryEntries(entries: string[]): string[] {
  return entries.filter((entry) => {
    const lastSegment = entry.split('/').pop() ?? entry;
    return SUPPORTED_IMAGE_FILE.test(lastSegment);
  });
}

function interleaveByPalette(entries: string[]): string[] {
  const bw: string[] = [];
  const color: string[] = [];
  const other: string[] = [];

  for (const entry of entries) {
    const normalized = entry.trim().replace(/^\/+/, '');
    if (normalized.startsWith('bw/')) {
      bw.push(entry);
    } else if (normalized.startsWith('color/')) {
      color.push(entry);
    } else {
      other.push(entry);
    }
  }

  if (!bw.length || !color.length) {
    return [...entries];
  }

  const mixed: string[] = [];
  const primary = color.length >= bw.length ? color : bw;
  const secondary = primary === color ? bw : color;
  const maxLength = Math.max(primary.length, secondary.length);

  for (let i = 0; i < maxLength; i += 1) {
    if (primary[i]) mixed.push(primary[i]);
    if (secondary[i]) mixed.push(secondary[i]);
  }

  return [...mixed, ...other];
}

const placement = galleryPlacement as GalleryPlacementFile;
const manifest = applyGalleryMoves(galleryManifest as GalleryManifest, placement.moves);
const categoryKeys = Object.keys(manifest).filter(
  (key) => key !== ABOUT_KEY && Array.isArray(manifest[key]) && (manifest[key]?.length ?? 0) > 0
);

function resolveAboutImagePath(entry: string): string {
  const normalized = entry.trim().replace(/^\/+/, '');
  if (!normalized) return '';
  return `${stillLifeBase}/${normalized}`;
}

const aboutFilename = (manifest[ABOUT_KEY] ?? []).find((filename) => SUPPORTED_IMAGE_FILE.test(filename));
export const ABOUT_IMAGE_SRC = aboutFilename
  ? resolveAboutImagePath(aboutFilename)
  : `${stillLifeBase}/about_me.jpg`;

export const COLLECTIONS: PhotoCollection[] = categoryKeys.map((category) => {
  const entries = selectGalleryEntries(manifest[category] ?? []);
  const ordered = applyOrderOverride(interleaveByPalette(entries), category, placement.order);
  return {
    id: category,
    title: toCategoryTitle(category),
    photos: photosFromEntries(ordered, category),
  };
});

export const GALLERY_FILTERS = COLLECTIONS.map((collection) => collection.id);
export const DEFAULT_GALLERY_FILTER = GALLERY_FILTERS[0] ?? '';

export const ABOUT = {
  name: 'adubsqz',
  tagline: 'Photography',
  contactEmail: 'adubsqz@gmail.com',
  bio: 'Originally from the Southwest, now residing in New York for several years, a rediscovered love for film photography, acting, and writing all came together, stars aligned, or dead weight dropped, either way. with film photography, first learning the craft in high school, spending long hours in the darkroom developing film and making silver prints—a passion that stayed dormant until recently. By trade, a data scientist and software engineer at a biomolecular research company focused on fighting cancer. At night, the world of cinema, art, and storytelling awaits. Bobs your uncle, adubs is your nephew rolling spliffs by the dumpster to make it through a dull family reunion.',
  socials: [
    { name: 'Instagram', url: 'https://www.instagram.com/adubsqz/' },
    { name: 'GitHub', url: 'https://github.com' },
  ],
};
